### ISSUE TITLE
Missing mariadb password deployment from values to Secret

### ISSUE THREAD

**Issue by MurzNN** [300481/seafile-server#4]
When re-deploing the chart, I see that `maridb-password` in Secret is always changing to new generated one:
```diff
Comparing release=my-seafile, chart=seafile/seafile
seafile, my-seafile-mariadb, Secret (v1) has changed:
  # Source: seafile/charts/mariadb/templates/secrets.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app.kubernetes.io/instance: my-seafile
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mariadb
      helm.sh/chart: mariadb-9.3.16
    name: my-seafile-mariadb
    namespace: seafile
  data:
-   mariadb-password: '-------- # (10 bytes)'
+   mariadb-password: '++++++++ # (10 bytes)'
    mariadb-root-password: 'REDACTED # (14 bytes)'
  type: Opaque
```
With `mariadb-root-password` all is ok, but `mariadb-password` always want to change on each new helm upgrade.

This happens even if I fill out the static value in `values-override.yaml`:
```yaml
mariadb:
  auth:
    password: myPassword
    rootPassword: myRootPassword
```

Meanwhile Seafile instance works well after upgrade, because it uses the root password (is it a good idea to use root password?):
```yaml 
      containers:
      - env:
        - name: DB_ROOT_PASSWD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: dg-seafile-mariadb
```

So, why mariadb regular password is always changed, and how to prevent this problem?
